@startuml

start
:Авторизация клиента в приложении;
:Выбор карты и тарифа;
:Заполнение заявки на открытие карты;
note left
 На форму подтягиваются данные
 пользователя: ФИО, дата рождения,
 паспортные данные и т.д.
 Для кредитных ещё доход и место работы
end note

@enduml
