@startuml

start
:Подача клиентом заявки на открытие вклада;
:Регистарция заявки;
:Инициализация проверок;
if (все проверки пройдены) then (нет)
 :Уведомить клиента о невозможности\n открыть вклад;
 end
else (да)
endif
:Открытие вклада;
:Перевод денег на вклад со счета клиента;
:Уведомить клиента об открытии вклада;
while (настала дата начисления процентов?) is (да)
 switch (способ перевода процентов)
  case (на вклад)
   :Перервести проценты на вклад;
  case (на карту)
   :Перевести проценты на карту;
  case (на карту другого банка)
   :Перевести проценты на карту в другой банк;
 endswitch
 if (день закрытия вклада?) then (нет)
  :Уведомить клиента о событии;
  end
 elseif(пролонгация вклада включена?) then (да)
  :Установить новую дату закрытия;
 else (нет)
  :Перевести деньги указанным способом;
  :Сформировать документы;
  :Уведомить клиента о событии;
end
 endif
endwhile (нет)
:Повторить проверку на следующий день;


@enduml

