@startuml

start
:Подача клиентом заявки на реструктуризацию;
note left
 Подать можно онлайн или в офисе
end note
:Регистрация заявки;
:Запуск первичных проверок;
if (Проверки пройдены успешно) then (Нет)
 #pink :Уведомление клиента об \nотрицательном решении;
 end
else (Да)
endif
:Запуск скоринга;
switch (Результат скоринга)
 case (доверительный)
  :Автоматическое формирование
  нового договора;
 case (сомнительный)
 partition #yellow UI внтуреннего специалиста {
  fork
   :Согласование заявки
   кредитным специалистом;
  fork again
   :Согласование заявки
   юристом;
  fork again
   :Согласование заявки
   безопасником;
  end fork {срок согласования\n 2 дня}
  }
  if (получено все три согласования?) then (Да)
  else (нет)
  #pink :Уведомление клиента об \nотрицательном решении;
  end
  endif
  :Формирование нового договора;
 case (рисковый)
 :Формирование отказа;
 #pink :Уведомление клиента об \nотрицательном решении;
 end
endswitch
:Отправка клиенту нового договора;
:Подписание догвора клиентом;
:Перерасчёт графика платежей;
end

@enduml
