@startuml

start

:Заполнить форму;
if (Разрешено ли сотруднику изменять баланс данного абонента?) then (Нет)
 :Уведомить о невозможности создать корректировку;
 end
 elseif (Надо создать для прошлого периода?) then (да)
   if(Можно ли создавать этот тип для прошлого периода?) then (Нет)
    :Уведомить о невозможности создать корректировку;
    end
   else (Да)
   endif
 else (нет)
endif
:Создать корректировку;
while (В списке остались лицевые счета?) is (Да)
 :Изменить баланс лицевого счета;
 switch (тип клиента)
  case (вип)
   :Установить большой промо-код;
  case (обычный)
   :Установить маленький промо-код;
 endswitch
 fork
  :Отправить смс оповещение;
 fork again
  :Создать СФ;
 end fork
 :Убрать лицевой счет из списка;
endwhile (нет)
:Уведомить об завершении обработки списка;
end

@enduml
