 ' Шаблон описания таблицы БД (в PlantUML)
@startuml

skinparam {
' Параметры для управления нижним колонтитулом
    FooterFontColor #blue
    FooterFontSize 12
' Параметры для управления легендой
    LegendBackgroundColor #lightblue
    LegendBorderThickness 0
}

' Переменные для ускорения описания таблицы
' - PRIMARY KEY можно указывать как: "$PK"
    !$PK="  <size:11><#DarkKhaki:key:></size> (PK)  "
' - FOREIGN KEY можно указывать как: "$FK"
    !$FK="  <size:11><#DeepPink:key:></size> (FK)  "
' - NOT NULL (N-N) можно указывать как: "$NN"
    !$NN="  <#LightGreen> **Not Null**  "
' - NULL можно указывать как: "$N"
    !$N = "  <#LightCoral> **NULL**  "


' Переменные для ускорения добавления информации о таблице
' - Наименование таблицы БД (латинское)
    !$table_name="Client"
' - Краткое описание таблицы (на русском)
    !$description="Описание клиента банка, у которого есть счёт"
' - Ссылка на описание таблицы (на русском)
    !$doc_url="Ссылка"

' Контакты, отображаемые в нижнем колонтитуле
    !$autor ="Романова Юлия"
    !$email ="rjo.ru"

' Заголовок документа, формируется автоматически из заполненных выше параметров (при необходимости можно удалить)
    title $table_name | $description

' Легенда (может быть заполнена любыми необходимыми данными)
' - "right" говорит о том, что легенда будет расположена справа
legend right
**Легенда:**
| Версия документа: | 1.0.0 |
end legend


' Описание таблицы
' - заголовок таблицы, с кликабельной ссылкой (если выгружать в SVG) формируется автоматически
class "[[$doc_url $table_name]] ($description)" as $table_name << (T,#FF5722) >>{

|=   PK,FK  |=   Поле   |=   Тип   |=   Обязательность   |=   Значение\n по умолчанию   |=   Описание   |
| $PK | id | uuid | $NN | | Идентификатор записи в таблице |
|     | first_name | string | $NN |  | Имя клиента |
|     | last_name | string | $NN |  | Фамилия клиента |
|     | phone | varchar(18) | $NN |  | Номер телефона, шаблон +7-(ххх)-ххх-хх-хх,\n где х - число от 0 до 9 |
|     | email | | $N | | Электронный адрес |
|     | date_birthday | date | $NN | | Дата рождения клиента |
| $FK | type_client_id | int | $NN | | Тип клиента. Идентификатор записи\n в таблице type_client |
|     | created_at | timestampz | $NN | now() | Дата и время создания записи в БД |
|     | updated_at | timestampz | $N | | Дата и время обновления записи в БД |
|     | is_active | bool | $NN | true | Признак логического удаления |
}

' Нижний колонтитул (формируется автоматически из введенных параметров)
footer $autor | email: $email
@enduml