@startuml

entity cat
{
  *PK id: int
  --
  name: string
  age: int
}

entity food
{
  *PK id: int
  --
  *name: string
  *FK type_food_id: int
  calories: decimal
}

entity type_food
{
  *PK id: int
  --
  *name: string
}

entity feeding_session
{
  *PK id: int
  --
  *FK food_id: int
  *FK cat_id: int
  date : timestamp
}

cat ||--|{ feeding_session
food "1..*" }o--|| "0..*" type_food
food }|--o{ feeding_session

@enduml

